apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: latihan-ns
spec:
  serviceAccountName: readonly-sa
  containers:
  - name: test
    image: bitnami/kubectl:latest
    command: ["sh", "-c", "sleep 3600"]
